[general]
import = [
  ## -- Font
  # "~/.config/alacritty/fonts/explex35.toml",
  "~/.config/alacritty/fonts/maple-mono.toml",
  # "~/.config/alacritty/fonts/monaspace.toml",
  # "~/.config/alacritty/fonts/moralerspace.toml",
  # "~/.config/alacritty/fonts/pleckjp.toml",
  # "~/.config/alacritty/fonts/plemoljp35.toml",
  ## -- Theme
  "@catppuccin_alacritty@",
]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
COLORTERM = "truecolor"
TERM = "alacritty-direct"
TERM_PROGRAM = "alacritty"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
program = "@zsh_path@"
args = ["--login"]

# TODO: for the future release
# [terminal]
# osc52 = "CopyOnly"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 0.9
option_as_alt = "None"
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 3
y = 3
