macos-non-native-fullscreen = true
macos-option-as-alt = true
macos-window-shadow = false
macos-auto-secure-input = true
macos-secure-input-indication = true
macos-titlebar-style = hidden

font-thicken = true
