# === Plugins (loaded on startup) ===

#==============================================================================
# Fundamentals
#==============================================================================

# Dark powered Vim/Neovim plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Enable configuration file in each directory
[[plugins]]
repo = 'thinca/vim-localrc'

# EditorConfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
if = 'executable("editorconfig")'
hook_add = '''
  let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
'''

#==============================================================================
# Interfaces
#==============================================================================

# Provides the branch name of the current git repository
[[plugins]]
repo = 'itchyny/vim-gitbranch'

# Faster than the built-in 'matchparen' plugin
[[plugins]]
repo = 'itchyny/vim-parenmatch'
#if = 'has("gui_running")'

# Visually displaying indent levels with thin vertical lines
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_enable = 1
  let g:indentLine_char = '¦'
  " Keep my conceal setting
  let g:indentLine_setConceal = 0
'''

# Better whitespace highlighting for Vim
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
  let g:better_whitespace_enabled = 1
  let g:strip_whitespace_on_save  = 1
  let g:show_spaces_that_precede_tabs = 1
  let g:better_whitespace_filetypes_blacklist = [
      \ 'diff', 'gitcommit', 'defx', 'denite', 'qf', 'help',
      \ 'markdown', 'which_key'
      \ ]

  nnoremap <silent><Leader>x  :<C-u>StripWhitespace<CR>
'''

# Seemless navitation between Tmux and Vim
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
  let g:tmux_navigator_no_mappings = 1
  nnoremap <silent><M-h>  :<C-u>TmuxNavigateLeft<CR>
  nnoremap <silent><M-j>  :<C-u>TmuxNavigateDown<CR>
  nnoremap <silent><M-k>  :<C-u>TmuxNavigateUp<CR>
  nnoremap <silent><M-l>  :<C-u>TmuxNavigateRight<CR>
  nnoremap <silent><M-\>  :<C-u>TmuxNavigatePrevious<CR>
  if has('terminal')
    tnoremap <silent><M-h>  :<C-u>TmuxNavigateLeft<CR>
    tnoremap <silent><M-j>  :<C-u>TmuxNavigateDown<CR>
    tnoremap <silent><M-k>  :<C-u>TmuxNavigateUp<CR>
    tnoremap <silent><M-l>  :<C-u>TmuxNavigateRight<CR>
  endif
'''

#==============================================================================
# Plugin dependencies (non-lazy loading)
#==============================================================================

# Find fenced code blocks and filetype (e.g., Javascript blocks inside HTML)
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# Operator extension
[[plugins]]
repo = 'kana/vim-operator-user'

# Textobj extension
[[plugins]]
repo = 'kana/vim-textobj-user'

# Powerful repeat '.'
[[plugins]]
repo = 'tpope/vim-repeat'

#==============================================================================
# Appearance
#==============================================================================

# Custom status line
[[plugins]]
repo = 'itchyny/lightline.vim'

# iceberg
[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
  let g:edge_style = 'aura'
  let g:edge_enable_italic = 1
  if !has('gui_running')
    let g:edge_transparent_background = 1
  endif
'''

#==============================================================================
# Syntax, filetype (not necessary for lazy loading)
#==============================================================================

# A collection of language packs for Vim
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
  let g:polyglot_disable = ['json', 'markdown']
'''

# Japanese Vim documentation 
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# D language
[[plugins]]
repo = 'JesseKPhillips/d.vim'

# Python
[[plugins]]
# extend % and g% for python
repo = 'vim-scripts/python_match.vim'

# JSON
[[plugins]]
repo = 'neoclide/jsonc.vim'

# zsh
[[plugins]]
repo = 'chrisbra/vim-zsh'

# GNU As
[[plugins]]
repo = 'Shirk/vim-gas'

