border = "#eff1f5"
accent = "#179299"
muted = "#9ca0b0"
text = "#cdd6f4"
text_sel = "#4c4f69"
key = "#dc8a78"
match = "#179299"
desc = "#a6adc8"
desc_sel = "#4c4f69"
sel_bg = "#ccd0da"
sel_text = "#eff1f5"
scroll_info = "#dc8a78"
ghost_text = "#9ca0b0"
sys = "#24273a"
sys_sel = "#fe640b"
hist = "#e6e9ef"
hist_sel = "#179299"
alias = "#24273a"
alias_sel = "#ea76cb"
