border = "#ca9ee6"
accent = "#81c8be"
muted = "#737994"
text = "#c6d0f5"
text_sel = "#c6d0f5"
key = "#ca9ee6"
match = "#a6d189"
desc = "#a5adce"
desc_sel = "#c6d0f5"
sel_bg = "#626880"
sel_text = "#303446"
scroll_info = "#ca9ee6"
ghost_text = "#626880"
sys = "#414559"
sys_sel = "#ef9f76"
hist = "#292c3c"
hist_sel = "#81c8be"
alias = "#414559"
alias_sel = "#ca9ee6"
