border = "#c6a0f6"
accent = "#8bd5ca"
muted = "#6e738d"
text = "#cad3f5"
text_sel = "#cad3f5"
key = "#c6a0f6"
match = "#a6da95"
desc = "#a5adcb"
desc_sel = "#cad3f5"
sel_bg = "#5b6078"
sel_text = "#24273a"
scroll_info = "#c6a0f6"
ghost_text = "#5b6078"
sys = "#363a4f"
sys_sel = "#f5a97f"
hist = "#1e2030"
hist_sel = "#8bd5ca"
alias = "#363a4f"
alias_sel = "#c6a0f6"
