border = "#cba6f7"
accent = "#94e2d5"
muted = "#6c7086"
text = "#cdd6f4"
text_sel = "#cdd6f4"
key = "#cba6f7"
match = "#a6e3a1"
desc = "#a6adc8"
desc_sel = "#cdd6f4"
sel_bg = "#585b70"
sel_text = "#1e1e2e"
scroll_info = "#cba6f7"
ghost_text = "#585b70"
sys = "#313244"
sys_sel = "#fab387"
hist = "#181825"
hist_sel = "#94e2d5"
alias = "#313244"
alias_sel = "#cba6f7"
