border = "#a277ff"
accent = "#61ffca"
muted = "#6d6a7f"
text = "#edecee"
text_sel = "#ffffff"
key = "#a277ff"
match = "#61ffca"
desc = "#9692a8"
desc_sel = "#edecee"
sel_bg = "#3d375e"
sel_text = "#110f18"
scroll_info = "#a277ff"
ghost_text = "#4B4A4C"
sys = "#1e1d28"
sys_sel = "#a277ff"
hist = "#1a2d36"
hist_sel = "#61ffca"
alias = "#2a2342"
alias_sel = "#a277ff"
