border = "#d79921"
accent = "#fabd2f"
muted = "#928374"
text = "#ebdbb2"
text_sel = "#fbf1c7"
key = "#d79921"
match = "#b8bb26"
desc = "#a89984"
desc_sel = "#ebdbb2"
sel_bg = "#3c3836"
sel_text = "#282828"
scroll_info = "#d79921"
ghost_text = "#665c54"
sys = "#32302f"
sys_sel = "#fb4934"
hist = "#282828"
hist_sel = "#83a598"
alias = "#32302f"
alias_sel = "#d3869b"