keys:
  - &admin_ikeno 692C3A45D7E6596AB81ABD715ECFDA6D2E4B4576
  - &host_lenneth age145t2t3vh3jeshw02fajsdxq0fq2m0xqvrnasujzs4zwc7g5j4s8qtwmgtu
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *admin_ikeno
        age:
          - *host_lenneth
  - path_regex: modules/sops/secrets.yaml$
    key_groups:
      - pgp:
          - *admin_ikeno
        age:
          - *host_lenneth
