default_provider = "age"

[leases.github]
type = "github-oauth"
client_id = "Iv23ct28bif8Nck421Ld"
scope = "repo read:org workflow"
duration = "8h"
env_var = "GITHUB_TOKEN"

[providers.age]
type = "age"
recipients = [
  "age15pxc0e7mktd86c953gue68zcsx40hymslx9m2daqxmhx58nqnqns93rrt8",
  "age14968q6wjwpny56k0eatnehmzxyr9ywr5z3lruc4p3g3xx7y7g5xq6hsxuk",
]

[secrets]
OPENAI_API_KEY = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHanFQVG9mbmNXcjBMT2hlS2txQ0ZJY0ZzUUVqR20rK3V4ZjFNSjFodUNJCmhIMENTWjd5T1BtZWJkUTJzOGhBRUdMOFJNZ3VyR1RZaVl6WGYyOFoyNUEKLT4gJStCLWdyZWFzZSAhYnIoU0s5ID05IGRQXUViKCMKei9GcjFnd1ZBQkh2SU1hZUxGUzM0dW1ETEkxOXJ2NE91dU9Id0toWGh2NXRncm9JczFTd1drUFNLRU1paVEKLS0tIFBjQmd6MUdORzlySkZVSVNvQ1ZibldkL2ZTalJIZzBoL0R5cnhLUFZ3eWcKF1uC4HvSCqWbQanlISm1WHU5CACi2iCNSqjx4keawKNg9Rj8vRUQ0WHTuLHlOqJcm8JpXwfEwWTOG9hBcNaI0QrikXAxHLxzl/UtoEdKoR6gDS3RYcZoHUWFxpjle6S64M9ICfYUYNFpnzoomoRAWDvBIMcCtMm6MRO7SvMMwkRjZbQFfS8ByGlZyh6GOdyyXFX31Fx8O7m6gW0zqI5fk5yPMTJsgWcSJryO5DZ/AL5qJ3OjQ82n15Ba5Ehr0bo06r8Yvw==" }
OPENROUTER_API_KEY = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVGtDeDJvd3lkYy92YWlXQmMvSUpaMU40RUdCTmZ0bi9vS0VacmFlRGhjCkFmU1Z3dVJkaFdWcjBIV09uSHk3M3VkYlJieEFPeGtrTllJZ2luenUvS0UKLT4gOi09InZbYC1ncmVhc2UgUUg5VkBhIDMhKFxMIEwiOQpHTDdNVFgvNlA0VDQ4MkkwVk4yR0RQeVNQSk1xK3lYTVo4YkVBU1FGTXNNLzdqTkhCei9admNaT3FrbjFZcWc3CmYvajdGbVFsY1FtUTl4dGZWc1ZiMXJaSm5IUVdjVzByTzlicjhnODRRVGlXCi0tLSAxTWhIeXV1V0JuWkNIOXhYd2VockNzNGNHZHJRZjByYkZCbUxmZmdBSHpjCmM15dU8cMqe3bdjEZIX3A3604xMn0Po27ygE2FOPHet0sxZs4aexLFSJ5ggldpz0crGa8HW6mEhCnFBgcGcbvebYUeJSuGZjP8aKZAdJAb5asDn7E8V3mYEeKvhXMvqDyd7C7H1A+5Tiw==" }
