default_provider = "age"

[leases.github]
type = "github-oauth"
client_id = "Iv23ct28bif8Nck421Ld"
scope = "repo read:org workflow"
duration = "8h"
env_var = "GITHUB_TOKEN"

[providers.age]
type = "age"
recipients = [
  "age15pxc0e7mktd86c953gue68zcsx40hymslx9m2daqxmhx58nqnqns93rrt8",
  "age14968q6wjwpny56k0eatnehmzxyr9ywr5z3lruc4p3g3xx7y7g5xq6hsxuk",
]

[secrets]
OPENAI_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZjVLVzhVQjZPdmxkRUhEVlkxY2ltblpXR2xtOGNBemVLWXFDUGpPMm5FCjVjTVpoeXFjSzBuRG0wQUxNTjF1eCt3allpd0V3TDRQTStVRitsYjhSeGcKLT4gWDI1NTE5IFVCRWUwQ1FYMndVWVBLV2g2MVZzZ2lmU3RrYk9wVHFWaDZNbWh6SldzU00KWUp3TnVPSU5nYU5ndjRMUno1TjR4dmlvekJDaEZKejU3NHQyckRsY2o4cwotPiB8O11HfC1ncmVhc2UgOTknPDsvLyA8L1xYU0c0ICdeJnc5KApFQ1FMQ1cyZVl3WHZZeUZnNkljUC9oR20zTVJ6RWVjMWFFdDIKLS0tIC9obmlKNTJ1S0U1R3NWTlNUUDNlNHV1TVZKRzhuV1drUklwb29PUzBNMDQKk4BS5xX2GmWFo1E72rUFjXFQsNeUe5ljp4h9+sPy6hSfb3ngJPmuXHNfGoXbrG5PbhneEigvbSxiczQr4jiUej9PmSJwPmxmlcsU1PLzcCzTma5RYpNR95NI5Opnt01n2UzDC5wp4yYOK2+uXdM0hbLWd/WDPtcAVdVwZaOavQpSZAiAc8ag96dTj3pbjj9wruSQvHxvLsXbe0KDiI/RbLzfj60wRjFH3+CR13kPm2VTfKtwedC8VxzqB0M8v+mFc03kLg==" }
OPENROUTER_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bC9nM01sd0w0c2lDVk9Rdi9zcUFFUHpkbFp3TnE1OW5JcU51S05ISkdrCllyMGRQbU0yMnRSVFpuY1JWNVh0WXBhMlU3NVFMV2JEWTFYRkM1Y3o1aU0KLT4gWDI1NTE5IDNqMmtOVW1NL3J1OTVTSCtkSmhrM0FsMEswREZHelp6cUZEZ0Q3V05oR0kKR3I2cEplU3ovNFlISW96dEV0bUhKRXRaMjNva2ROeHNMV3dXby9jWmZZRQotPiA/LWdyZWFzZSBrNy93aFQgW2luMgpUTGMwbkxIcyt6RHljMzU5eS9keTNLQ0FOK29PM2xXTzNRcUo3Sy9pOEx3RFFRZlRQbUZxTDVsOHh5SnFXY09MCmJnCi0tLSBJbnJERXVHVGtmOHMzd1NWb3VOWXNSYlNUVGcycHVRRWVna3JUcU5Zc09ZCuVVY82tKWFmJi0bog2fwUb2RkF33on362kwn9NqF5scfEea+b6texgGQk0DCuSX9qzasb4KbuQ56mLHbL3llupMdWewAbsH0P/431sYg/FMQjOffnSPZlfaGm79kZTOdVAXwb8T/jsnNw==" }
