# Kanagawa Lotus Alacritty Colors

[colors.primary]
background = '#f2ecbc'
foreground = '#545464'

[colors.normal]
black = "#1f1f28"
red = "#c84053"
green = "#6f894e"
yellow = "#77713f"
blue = "#4d699b"
magenta = "#b35b79"
cyan = "#597b75"
white = "#545464"

[colors.bright]
black = "#8a8980"
red = "#d7474b"
green = "#6e915f"
yellow = "#836f4a"
blue = "#6693bf"
magenta = "#624c83"
cyan = "#5e857a"
white = "#43436c"

[colors.selection]
background = '#c9cbd1'
foreground = '#dcd7ba'

[[colors.indexed_colors]]
index = 16
color = '#e98a00'

[[colors.indexed_colors]]
index = 17
color = '#e82424'
