# === Plugins managed by dein.vim (non-lazy) ====

#==============================================================================
# Plugin manager
#==============================================================================

# Dark powered Vim/Neovim plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

#==============================================================================
# Libraries used by other plugins
#==============================================================================

# Find fenced code blocks and filetype (e.g., Javascript blocks inside HTML)
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# Operator extension
[[plugins]]
repo = 'kana/vim-operator-user'

# Textobjextension
[[plugins]]
repo = 'kana/vim-textobj-user'

# Powerful repeat '.'
[[plugins]]
repo = 'tpope/vim-repeat'

# Original popup completion menu framework library
[[plugins]]
repo = 'Shougo/pum.vim'

#==============================================================================
# Extensions of standard features
#==============================================================================

# === Folding ===
# [[plugins]]
# repo = 'vim-jp/autofmt'
# hook_add = '''
# set formatexpr=autofmt#japanese#formatexpr()
# '''

#==============================================================================
# Treesitter
#==============================================================================
[[plugins]]
repo = 'mattn/vim-treesitter'
build = 'cd server && go build'
if = '!has("nvim")'

#==============================================================================
# Programming languages
#==============================================================================
# -- Python
# extend % and g% for python
[[plugins]]
repo = 'vim-scripts/python_match.vim'

# -- Vim
# Vim help (Japanese)
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# An excellent Vim's syntax highlighting file for Vim script.
[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

# Vim script's indentexpr supporting legacy Vim script syntax and Vim9 script
# syntax if possible.
[[plugins]]
repo = 'rbtnn/vim-vimscript_indentexpr'

# -- TOML
# Vim syntax for TOML
[[plugins]]
repo = 'cespare/vim-toml'

# -- Zsh
# Official Vim Runtime Files for Zsh
[[plugins]]
repo = 'chrisbra/vim-zsh'

# -- GNU As
# Advanced syntax highlighting for GNU As
[[plugins]]
repo = 'Shirk/vim-gas'

