[metadata]
name = "ghq"
description = "A channel to select remote repository clones managed by ghq"
requirements = ["ghq"]

[source]
command = "ghq list --full-path"

[preview]
command = "ls -a '{}'"
