##============================================================================
## Auto completions
##============================================================================

# Dark deno-powered completion framework for neovim/Vim
[[plugins]]
repo = 'Shougo/ddc.vim'
depends = 'denops.vim'
on_event = 'InsertEnter'
hooks_file = '$VIM_CONFIG_DIR/dpp/config/ddc.lua'

##
## UIs for ddc.vim
##

# Original popup completion menu framework library
[[plugins]]
repo = 'Shougo/pum.vim'

# Native popup menu UI for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'

# pum.vim UI for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = 'pum.vim'
on_source = 'ddc.vim'

# Inline UI for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-ui-inline'
on_source = 'ddc.vim'

# None UI for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-ui-none'
on_source = 'ddc.vim'

# A previewer for ddc.vim in Neovim.
[[plugins]]
repo = 'uga-rosa/ddc-previewer-floating'
on_source = 'ddc.vim'

##
## Completion sources for ddc.vim
##

# Around completion for ddc.vim.
# This source collects items around the cursor, namely inside current buffer.
[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

# Command line completion for ddc.vim
# This source collects items from getcompletion('cmdline').
[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
on_source = 'ddc.vim'

# Command history completion for ddc.vim
# This source collects items from `histget()`.
[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'
on_source = 'ddc.vim'

# `input()` completion for ddc.vim. It works only for command line mode.
[[plugins]]
repo = 'Shougo/ddc-source-input'
on_source = 'ddc.vim'

# Line completion for ddc.vim
# This source collects items from current buffer lines.
[[plugins]]
repo = 'Shougo/ddc-source-line'
on_source = 'ddc.vim'

# LSP source for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = 'ddc.vim'

# `rg` completion for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-source-rg'
on_source = 'ddc.vim'

# Buffer source for ddc.vim
[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

# Powerful and performant file name completion for ddc.vim.
[[plugins]]
repo = 'LumaKernel/ddc-source-file'
on_source = 'ddc.vim'

# ddc.vim source that completes from like yanked buffer
[[plugins]]
repo = 'kuuote/ddc-source-yank'
on_source = 'ddc.vim'
# hook_add = '''
#   nnoremap cd <Cmd>call ddc#source#yank#clear()<CR>
#   nnoremap cy <Cmd>set operatorfunc=ddc#source#yank#register<CR>g@
#   xnoremap Y <Cmd>set operatorfunc=ddc#source#yank#register<CR>g@
# '''

# The Vim Script completion source for neocomplete/deoplete/ddc
 [[plugins]]
 repo = 'Shougo/neco-vim'
 on_ft = ['vim', 'toml', 'markdown']
 depends = 'ddc.vim'

##
## Filters for ddc.vim
##

 [[plugins]]
 repo = 'Shougo/ddc-filter-matcher_head'
 on_source = 'ddc.vim'

# Length matcher for ddc.vim
 [[plugins]]
 repo = 'Shougo/ddc-filter-matcher_length'
 on_source = 'ddc.vim'

 [[plugins]]
 repo = 'Shougo/ddc-filter-matcher_prefix'
 on_source = 'ddc.vim'

 [[plugins]]
 repo = 'Shougo/ddc-filter-sorter_head'
 on_source = 'ddc.vim'

 [[plugins]]
 repo = 'Shougo/ddc-filter-sorter_rank'
 on_source = 'ddc.vim'

 [[plugins]]
 repo = 'Shougo/ddc-filter-matcher_vimregexp'
 on_source = 'ddc.vim'

# Remove overlapped text converter for ddc.vim
 [[plugins]]
 repo = 'Shougo/ddc-filter-converter_remove_overlap'
 on_source = 'ddc.vim'

# Truncate abbr converter for ddc.vim
 [[plugins]]
 repo = 'Shougo/ddc-filter-converter_truncate_abbr'
 on_source = 'ddc.vim'

# Fuzzy matcher, sorter, and conveter for ddc.vim
 [[plugins]]
 repo = 'tani/ddc-fuzzy'
 on_source = 'ddc.vim'
