##============================================================================
## Auto completions
##============================================================================

# Dark deno-powered completion framework for neovim/Vim
[[plugins]]
repo = 'Shougo/ddc.vim'
depends = 'denops.vim'
on_event = 'InsertEnter'
hooks_file = '$DPP_HOOKS_DIR/ddc/ddc.lua'

##
## UIs for ddc.vim
##

# Original popup completion menu framework library
[[plugins]]
repo = 'Shougo/pum.vim'
hooks_file = '$DPP_HOOKS_DIR/pum.lua'

# Native popup menu UI for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'

# pum.vim UI for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = 'pum.vim'
on_source = 'ddc.vim'

# Inline UI for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-ui-inline'
on_source = 'ddc.vim'

# None UI for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-ui-none'
on_source = 'ddc.vim'

# A previewer for ddc.vim in Neovim.
[[plugins]]
repo = 'uga-rosa/ddc-previewer-floating'
on_source = 'ddc.vim'

##
## Completion sources for ddc.vim
##

# Around completion for ddc.vim.
# This source collects items around the cursor, namely inside current buffer.
[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

# Command line completion for ddc.vim
# This source collects items from getcompletion('cmdline').
[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
on_source = 'ddc.vim'

# Command history completion for ddc.vim
# This source collects items from `histget()`.
[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'
on_source = 'ddc.vim'

# `input()` completion for ddc.vim. It works only for command line mode.
[[plugins]]
repo = 'Shougo/ddc-source-input'
on_source = 'ddc.vim'

# Line completion for ddc.vim
# This source collects items from current buffer lines.
[[plugins]]
repo = 'Shougo/ddc-source-line'
on_source = 'ddc.vim'

# LSP source for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = 'ddc.vim'

# Omnifunc completion for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-source-omni'
on_source = 'ddc.vim'

# `rg` completion for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-source-rg'
on_source = 'ddc.vim'

# Shell completion for ddc.vim
# This source collects items from getcompletion(). It is useful for shell commands.
[[plugins]]
repo = 'Shougo/ddc-source-shell'
on_source = 'ddc.vim'

# Shell native completion for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-source-shell-native'
on_source = 'ddc.vim'

# Additional Vim script completion for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-source-vim'
on_source = 'ddc.vim'

# Buffer source for ddc.vim
[[plugins]]
repo = 'matsui54/ddc-source-buffer'
on_source = 'ddc.vim'

# Powerful and performant file name completion for ddc.vim.
[[plugins]]
repo = 'LumaKernel/ddc-source-file'
on_source = 'ddc.vim'

# Powerful and performant file name completion for ddc.vim.
[[plugins]]
repo = 'uga-rosa/ddc-source-nvim-lua'
on_source = 'ddc.vim'

# ddc.vim source that completes from like yanked buffer
[[plugins]]
repo = 'kuuote/ddc-source-yank'
on_source = 'ddc.vim'
# hook_add = '''
#   nnoremap cd <Cmd>call ddc#source#yank#clear()<CR>
#   nnoremap cy <Cmd>set operatorfunc=ddc#source#yank#register<CR>g@
#   xnoremap Y <Cmd>set operatorfunc=ddc#source#yank#register<CR>g@
# '''

##
## Filters for ddc.vim
##

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
on_source = 'ddc.vim'

# Length matcher for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-filter-matcher_length'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_prefix'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_vimregexp'
on_source = 'ddc.vim'

# Remove overlapped text converter for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'
on_source = 'ddc.vim'

# Truncate abbr converter for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-filter-converter_truncate_abbr'
on_source = 'ddc.vim'

# Fuzzy matcher, sorter, and conveter for ddc.vim
[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

##============================================================================
## Snippet plugins
##============================================================================
# A snippet plugin for Vim/Neovim, powered by TypeScript.
[[plugins]]
repo = 'github.com/uga-rosa/denippet.vim'
depends = ['denops.vim', 'denippet-autoimport-vscode', 'friendly-snippets']
on_source = 'ddc.vim'
hooks_file = '$DPP_HOOKS_DIR/denippet.lua'

# The simple module to autoload VS Code-like snippets on runtime path automatically.
[[plugins]]
repo = 'github.com/ryoppippi/denippet-autoimport-vscode'

# Set of preconfigured snippets for different languages.
[[plugins]]
repo = 'github.com/rafamadriz/friendly-snippets'
