##=============================================================================
## Fuzzy finder
##=============================================================================

[[plugins]] # ddu.vim
# Dark deno-powered UI framework for neovim/Vim
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
on_func = 'ddu#start'
hooks_file = '$DPP_HOOKS_DIR/ddu.lua'

# Commands for ddu.vim
[[plugins]] # ddu-commands.vim
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'

##
## UI
##
# Fuzzy finder UI for ddu.vim (This UI is standard fuzzy finder)
[[plugins]] # ddu-ui-ff
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
depends = ['cmdline.vim']
#hooks_file = '$DPP_HOOKS_DIR/ddu-ui-ff.lua'

# File listing UI for ddu.vim
[[plugins]] # ddu-ui-ff
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
# hooks_file = '$DPP_HOOKS_DIR/ddu-ui-filer.lua'

# Replace `vim.ui.select()` with ddu's UI (only for Neovim)
[[plugins]] # ddu-vim-ui-select
repo = 'matsui54/ddu-vim-ui-select'
on_source = 'ddu.vim'

##
## Sources
##

# Command args
[[plugins]] # ddu-source-command_args
repo = 'Shougo/ddu-source-command_args'
on_source = 'ddu.vim'

# Dummy items
[[plugins]] # ddu-source-dummy
repo = 'Shougo/ddu-source-dummy'
on_source = 'ddu.vim'

# Files in path
[[plugins]] # ddu-source-file
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

# Files in path recursivelly
[[plugins]] # ddu-source-file_rec
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

# File from v:oldfiles
[[plugins]] # ddu-source-file_old
repo = 'Shougo/ddu-source-file_old'
on_source = 'ddu.vim'

# Current line of filename format
[[plugins]] # ddu-source-file_point
repo = 'Shougo/ddu-source-file_point'
on_source = 'ddu.vim'

# Current buffer lines
[[plugins]] # ddu-source-line
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'

# Register
[[plugins]] # ddu-source-register
repo = 'Shougo/ddu-source-register'
on_source = 'ddu.vim'

# Actions
[[plugins]] # ddu-source-action
repo = 'Shougo/ddu-source-action'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-git_diff
repo = 'kuuote/ddu-source-git_diff'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-git_status
repo = 'kuuote/ddu-source-git_status'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-git_branch
repo = 'github.com/kyoh86/ddu-source-git_branch'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-git_log
repo = 'github.com/kyoh86/ddu-source-git_log'
on_source = 'ddu.vim'

# Path history from current ddu UI
[[plugins]] # ddu-source-path_history
repo = 'Shougo/ddu-source-path_history'
on_source = 'ddu.vim'

# Vim Ex-command output
[[plugins]] # ddu-source-output
repo = 'Shougo/ddu-source-output'
on_source = 'ddu.vim'

# File sources using external command
[[plugins]] # ddu-source-file_external
repo = 'matsui54/ddu-source-file_external'
on_source = 'ddu.vim'

# Command line history
[[plugins]] # ddu-source-command_history
repo = 'matsui54/ddu-source-command_history'
on_source = 'ddu.vim'

# Vim help tags
[[plugins]] # ddu-source-help
repo = 'matsui54/ddu-source-help'
on_source = 'ddu.vim'

# Buffers
[[plugins]] # ddu-source-buffer
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

# Buffers
[[plugins]] # ddu-source-buffer
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

# Ripgrep
[[plugins]] # ddu-source-rg
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

# Markdown headers
[[plugins]] # ddu-source-markdown
repo = 'mikanIchinose/ddu-source-markdown'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-mr
repo = 'kuuote/ddu-source-mr'
depends = ['vim-mr']
on_source = 'ddu.vim'

[[plugins]] # ddu-source-jumplist
repo = 'kamecha/ddu-source-jumplist'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-nvim-notify
repo = 'yuki-yano/ddu-source-nvim-notify'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-lsp
repo = 'uga-rosa/ddu-source-lsp'
on_source = 'ddu.vim'

##
## Filters (matcher, sorter, converter)
##
[[plugins]] # ddu-filter-matcher_files
repo = 'Shougo/ddu-filter-matcher_files'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-matcher_hidden
repo = 'Shougo/ddu-filter-matcher_hidden'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-matcher_ignore_files
repo = 'Shougo/ddu-filter-matcher_ignore_files'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-matcher_ignoores
repo = 'Shougo/ddu-filter-matcher_ignores'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-matcher_relative
repo = 'Shougo/ddu-filter-matcher_relative'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-matcher_substring
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-sorter_alpha
repo = 'Shougo/ddu-filter-sorter_alpha'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-converter_display_word
repo = 'Shougo/ddu-filter-converter_display_word'
on_source = 'ddu.vim'

[[plugins]] # ddu-column-filename
# Filename column for ddu.vim
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-fzf
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-sorter_mtime
repo = 'kuuote/ddu-filter-sorter_mtime'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-converter_hl_dir
repo = 'kyoh86/ddu-filter-converter_hl_dir'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-kensaku
repo = 'Milly/ddu-filter-kensaku'
depends = 'kensaku.vim'
on_source = 'ddu.vim'

# Icon and filename column for ddu.vim
[[plugins]] # ddu-column-icon_filename
repo = 'ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'

##
## Kind
##
# File kind for ddu.vim
[[plugins]] # ddu-kind-file
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

# Word kind for ddu.vim
[[plugins]] # ddu-kind-word
repo = 'Shougo/ddu-kind-word'
on_source = 'ddu.vim'

# URL kind for ddu.vim
[[plugins]] # ddu-kind-url
repo = '4513ECHO/ddu-kind-url'
on_source = 'ddu.vim'

