##=============================================================================
## Fuzzy finder
##=============================================================================

# Dark deno-powered UI framework for neovim/Vim
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
on_func = 'ddu#start'
hooks_file = '$DPP_HOOKS_DIR/ddu.lua'

# Commands for ddu.vim
[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'

##
## UI
##
# Fuzzy finder UI for ddu.vim (This UI is standard fuzzy finder)
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
depends = ['cmdline.vim']
hooks_file = '$DPP_HOOKS_DIR/ddu-ui-ff.lua'

# File listing UI for ddu.vim
[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
# hooks_file = '$DPP_HOOKS_DIR/ddu-ui-filer.lua'

# Replace `vim.ui.select()` with ddu's UI (only for Neovim)
[[plugins]]
repo = 'matsui54/ddu-vim-ui-select'
on_source = 'ddu.vim'

##
## Sources
##

# Command args
[[plugins]]
repo = 'Shougo/ddu-source-command_args'
on_source = 'ddu.vim'

# Dummy items
[[plugins]]
repo = 'Shougo/ddu-source-dummy'
on_source = 'ddu.vim'

# Files in path
[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

# Files in path recursivelly
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

# File from v:oldfiles
[[plugins]]
repo = 'Shougo/ddu-source-file_old'
on_source = 'ddu.vim'

# Current line of filename format
[[plugins]]
repo = 'Shougo/ddu-source-file_point'
on_source = 'ddu.vim'

# Current buffer lines
[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'

# Register
[[plugins]]
repo = 'Shougo/ddu-source-register'
on_source = 'ddu.vim'

# Actions
[[plugins]]
repo = 'Shougo/ddu-source-action'
on_source = 'ddu.vim'

# Path history from current ddu UI
[[plugins]]
repo = 'Shougo/ddu-source-path_history'
on_source = 'ddu.vim'

# Vim Ex-command output
[[plugins]]
repo = 'Shougo/ddu-source-output'
on_source = 'ddu.vim'

# File sources using external command
[[plugins]]
repo = 'matsui54/ddu-source-file_external'
on_source = 'ddu.vim'

# Command line history
[[plugins]]
repo = 'matsui54/ddu-source-command_history'
on_source = 'ddu.vim'

# Vim help tags
[[plugins]]
repo = 'matsui54/ddu-source-help'
on_source = 'ddu.vim'

# Buffers
[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

# Ripgrep
[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

# Markdown headers
[[plugins]]
repo = 'mikanIchinose/ddu-source-markdown'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-jumplist'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-source-nvim-notify'
on_source = 'ddu.vim'

##
## Filters (matcher, sorter, converter)
##
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_files'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_ignore_files'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_ignores'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_relative'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-sorter_alpha'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kuuote/ddu-filter-sorter_mtime'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-converter_display_word'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kyoh86/ddu-filter-converter_hl_dir'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Milly/ddu-filter-kensaku'
depends = 'kensaku.vim'
on_source = 'ddu.vim'

##
## Kind
##
# File kind for ddu.vim
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

# Word kind for ddu.vim
[[plugins]]
repo = 'Shougo/ddu-kind-word'
on_source = 'ddu.vim'

# URL kind for ddu.vim
[[plugins]]
repo = '4513ECHO/ddu-kind-url'
on_source = 'ddu.vim'

##
## Column
##
[[plugins]]
# Filename column for ddu.vim
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'

# Icon and filename column for ddu.vim
[[plugins]]
repo = 'github.com/ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'

