#=============================================================================
# Dark powered plugin manager for Vim/neovim
#=============================================================================
[[plugins]]
repo = 'Shougo/dpp.vim'
rtp = ''

# --- extensions ---
[[plugins]]
repo = 'Shougo/dpp-ext-lazy'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-ext-installer'

[[plugins]]
repo = 'Shougo/dpp-ext-local'

[[plugins]]
repo = 'Shougo/dpp-ext-packspec'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'
