#==============================================================================
# Coding
#==============================================================================
# Vim plugin: Define your own operator easily
[[plugins]]
repo = 'kana/vim-operator-user'

# Vim plugin: Create your own text objects
[[plugins]]
repo = 'kana/vim-textobj-user'

#==============================================================================
# Syntax,Filetypes
#==============================================================================
# A project which translate Vim documents into Japanes
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# An excellent Vim's syntax highlighting file for Vim script
[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

# Vim syntax for TOML
[[plugins]]
repo = 'cespare/vim-toml'

# A nicer Python indentation style for vim.
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

# Highlight dotfiles you manage with chezmoi.
[[plugins]]
repo = 'alker0/chezmoi.vim'

#==============================================================================
# Colorscheme
#==============================================================================
[[plugins]]
repo = 'catppuccin/nvim'
name = 'catppuccin'
hooks_file = '$DPP_HOOKS_DIR/catppuccin.lua'

