local data = {
  cmp = {
    Copilot = "",
    Copilot_alt = "",
    nvim_lsp = "",
    nvim_lua = "",
    path = "",
    buffer = " ",
    calc = "",
    emoji = "ﲃ",
    spell = "暈",
    latex_symbols = "",
    luasnip = "",
    treesitter = "",
  },
  dap = {
    Breakpoint = "ß",
    BreakpointCondition = "ﳁ",
    BreakpointRejected = "",
    LogPoint = "",
    Pause = "",
    Play = "",
    RunLast = "↻",
    StepBack = "",
    StepInto = "",
    StepOut = "",
    StepOver = "",
    Stopped = "ඞ",
    Terminate = "ﱢ",
  },
  diagnostics = {
    Error = "",
    Warning = "",
    Information = "",
    Question = "",
    Hint = "",
    -- Holo version
    Error_alt = "",
    Warning_alt = "",
    Information_alt = "",
    Question_alt = "",
    Hint_alt = "",
  },
  git = {
    Add = "",
    Branch = "",
    Diff = "",
    Git = "",
    Ignore = "",
    Mod = "M",
    Mod_alt = "",
    Remove = "",
    Rename = "",
    Repo = "",
    Unmerged = "שׂ",
    Untracked = "U",
    Unstaged = "",
    Staged = "",
    Conflict = "",
  },
  kind = {
    Class = "ﴯ",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Keyword = "",
    Method = "",
    -- Module = "",
    Module = "",
    Namespace = "",
    Number = "#",
    Operator = "",
    -- Package = "",
    Package = "",
    Property = "ﰠ",
    Reference = "",
    Snippet = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
    -- ccls-specific icons.
    TypeAlias = "",
    Parameter = "",
    StaticMethod = "",
    Macro = "",
  },
  type = {
    -- Array = "",
    Array = "",
    Boolean = "",
    Null = "ﳠ",
    Number = "#",
    Object = "⦿",
    String = "",
  },
}

return data
