# === Plugins (loaded on startup) ===

#==============================================================================
# Fundamentals
#==============================================================================

# Dark powered Vim/Neovim plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Speed up loading Lua modules in Neovim to improve startup time.
[[plugins]]
repo = 'lewis6991/impatient.nvim'
merged = 0

# EditorConfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
if = 'executable("editorconfig")'
hook_add = '''
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
'''

# Collection of minimal, independent, and fast Lua modules dedicated to improve Neovim experience.
[[plugins]]
repo = 'echasnovski/mini.nvim',
hook_add = 'lua require("rc.config.mini").config()'

#==============================================================================
# Appearance
#==============================================================================
[[plugins]]
repo = 'EdenEast/nightfox.nvim'

#==============================================================================
# Interfaces
#==============================================================================

# Show keybindings in popup
[[plugins]]
repo = 'folke/which-key.nvim'
hook_add = 'lua require "rc.config.which-key"'

#==============================================================================
# Plugin dependencies (non-lazy loading)
#==============================================================================

# Operator extension
[[plugins]]
repo = 'kana/vim-operator-user'

# Textobj extension
[[plugins]]
repo = 'kana/vim-textobj-user'

# Powerful repeat '.'
[[plugins]]
repo = 'tpope/vim-repeat'

#==============================================================================
# Syntax, filetype (not necessary for lazy loading)
#==============================================================================
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# D language
[[plugins]]
repo = 'JesseKPhillips/d.vim'

# Python
[[plugins]]
# extend % and g% for python
repo = 'vim-scripts/python_match.vim'

# JSON
[[plugins]]
repo = 'neoclide/jsonc.vim'

# zsh
[[plugins]]
repo = 'chrisbra/vim-zsh'

# GNU As
[[plugins]]
repo = 'Shirk/vim-gas'

