##
## CLI tools
##
[tools]
atuin = "latest"
bat = "latest"
bitwarden = "latest"
carapace = "latest"
delta = "latest"
difftastic = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fx = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
git-lfs = "latest"
glow = "latest"
gping = "latest"
herdr = "latest"
hk = "latest"
hunk = "latest"
hyperfine = "latest"
jaq = "latest"
jd = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
neovim = "nightly"
ripgrep = "latest"
ripgrep-all = "latest"
sheldon = "latest"
starship = "latest"
tmux = "latest"
tokei = "latest"
tree-sitter = "latest"
usage = "latest"
yazi = "latest"
yj = "latest"
yq = "latest"
"github:versenilvis/iris" = "latest"
"github:jrmoulton/tmux-sessionizer" = "latest"
"github:ajeetdsouza/zoxide" = "latest"
"github:michel-kraemer/zsh-patina" = "latest"

##
## Secrets
##
age = "latest"
fnox = "latest"

##
## Coding agents
##
claude = "latest"
codex = "latest"
gemini-cli = "latest"
